### ISSUE TITLE
Please update implementation references to reflect their  feature updates

### ISSUE THREAD

**Issue by anirajk** [kurin/py-raft#2]
I was going through a couple of implementations and to my novice eye, it felt that  py-raft by Toby Buress at least conforms to the Leader Election + Log Replication property. They also had an implementation of member changes which I could not really understand. Someone well versed in python and raft should be able to do a quick review of the row.

It'll be great if experts took a look at existing references and update their feature columns in addition to adding references since this github io page is a major reference when someone looks up raft.

**Comment by kurin** [comment]
Did you mean to open that bug with this project?

I wrote this to get my head around the raft algorithm.  Before py-raft is going to be used as a reference, I'd want to clean it up a whole lot, because wow such mess.

**Comment by anirajk** [comment]
I'm sorry, I meant to open a  bug on https://github.com/raftconsensus/raftconsensus.github.io
