### ISSUE TITLE
How to install and run?  Use case examples?

### ISSUE THREAD

**Issue by rwerthman** [kurin/py-raft#8]
Hello,

Can you put in the Readme how you install and run this?  Then how to remove it. Also, give a use case of setting up 3 servers and one client and then issuing commands from the client to the servers and checking that the command is replicated to all servers.

For my Distributed Systems class I am supposed to download an implementation of raft and add some extra functionality.  This seemed the best implementation in python I could find.

This is a tall order but it is appreciated.

**Comment by kurin** [comment]
I haven't really touched this code in years.  You can install and remove it via setup.py, and from what I recall it sort of works, but no promises.  Maybe one of the forks has made further progress?

If you're willing to look at other languages, etcd is a stable, production-worthy implementation in Go.

**Comment by rwerthman** [comment]
Ok, cool!  Thanks for getting back to me so quickly!  I'll take a look at etcd.
